export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';
export const UPDATE_GAME_RESULT = 'UPDATE_GAME_RESULT';
export const UPDATE_WINNER_NOUGHT_AND_CROSS = 'UPDATE_WINNER_NOUGHT_AND_CROSS';
export const UPDATE_READY_TO_PLAY = 'UPDATE_READY_TO_PLAY';
export const UPDATE_PLAYING = 'UPDATE_IS_PLAYING'