export const UPDATE_GAME_VIEW = 'UPDATE_GAME_VIEW';
export const UPDATE_GAME_SOUND = 'UPDATE_GAME_SOUND';
export const UPDATE_PLAYER_ONE_NAME = 'UPDATE_PLAYER_ONE_NAME';
export const UPDATE_PLAYER_TWO_NAME = 'UPDATE_PLAYER_TWO_NAME';
export const SWITCH_PLAYER_NOUGHT_CROSS_CHOICE = 'SWITCH_PLAYER_NOUGHT_CROSS_CHOICE';
export const UPDATE_READY_TO_PLAY = 'UPDATE_READY_TO_PLAY';
export const UPDATE_PLAYING = 'UPDATE_IS_PLAYING'