export const UPDATE_GAME_VIEW = 'UPDATE_GAME_VIEW';
export const UPDATE_GAME_SOUND = 'UPDATE_GAME_SOUND';
export const UPDATE_PLAYER_ONE_NAME = 'UPDATE_PLAYER_ONE_NAME';
export const UPDATE_PLAYER_TWO_NAME = 'UPDATE_PLAYER_TWO_NAME';
export const SWITCH_PLAYER_NOUGHT_CROSS_CHOICE = 'SWITCH_PLAYER_NOUGHT_CROSS_CHOICE';
export const RESET_GAME_MENU = 'RESET_GAME_MENU';