export const UPDATE_CURRENT_PLAYER = 'UPDATE_CURRENT_PLAYER';
export const UPDATE_GAME_BOARD_ARRAY = 'UPDATE_GAME_BOARD_ARRAY';
export const PUSH_TO_CROSS_SEQUENCE = 'PUSH_TO_CROSS_SEQUENCE';
export const PUSH_TO_NOUGHT_SEQUENCE = 'PUSH_TO_NOUGHT_SEQUENCE';